ignored = [ "github.com/inconshreveable/mousetrap" ]

[[constraint]]
  branch = "master"
  name = "github.com/ftrvxmtrx/fd"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/copier"

[[constraint]]
  branch = "master"
  name = "github.com/kr/pretty"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "v2"
  name = "github.com/zrepl/yaml-config"

[[constraint]]
  name = "github.com/go-logfmt/logfmt"
  version = "*"

[[constraint]]
  name = "github.com/problame/go-rwccmd"
  branch = "master"

[[constraint]]
  name = "github.com/problame/go-netssh"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"


[[constraint]]
  name = "github.com/gdamore/tcell"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-playground/validator"
  version = "9.23.0"
